// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: upmuStructKeyValueListProtobuf.proto

package serviceCommon;

public final class UpmuStructKeyValueListProtobuf {
  private UpmuStructKeyValueListProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KeyValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serviceCommon.KeyValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>optional int32 integerVal = 2;</code>
     */
    boolean hasIntegerVal();
    /**
     * <code>optional int32 integerVal = 2;</code>
     */
    int getIntegerVal();

    /**
     * <code>optional uint32 uIntegerVal = 3;</code>
     */
    boolean hasUIntegerVal();
    /**
     * <code>optional uint32 uIntegerVal = 3;</code>
     */
    int getUIntegerVal();

    /**
     * <code>optional float floatVal = 4;</code>
     */
    boolean hasFloatVal();
    /**
     * <code>optional float floatVal = 4;</code>
     */
    float getFloatVal();

    /**
     * <code>optional string stringVal = 5;</code>
     */
    boolean hasStringVal();
    /**
     * <code>optional string stringVal = 5;</code>
     */
    java.lang.String getStringVal();
    /**
     * <code>optional string stringVal = 5;</code>
     */
    com.google.protobuf.ByteString
        getStringValBytes();
  }
  /**
   * Protobuf type {@code serviceCommon.KeyValue}
   */
  public static final class KeyValue extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:serviceCommon.KeyValue)
      KeyValueOrBuilder {
    // Use KeyValue.newBuilder() to construct.
    private KeyValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeyValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeyValue defaultInstance;
    public static KeyValue getDefaultInstance() {
      return defaultInstance;
    }

    public KeyValue getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeyValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              key_ = bs;
              break;
            }
            case 16: {
              valueCase_ = 2;
              value_ = input.readInt32();
              break;
            }
            case 24: {
              valueCase_ = 3;
              value_ = input.readUInt32();
              break;
            }
            case 37: {
              valueCase_ = 4;
              value_ = input.readFloat();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              valueCase_ = 5;
              value_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return serviceCommon.UpmuStructKeyValueListProtobuf.internal_static_serviceCommon_KeyValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return serviceCommon.UpmuStructKeyValueListProtobuf.internal_static_serviceCommon_KeyValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.class, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.Builder.class);
    }

    public static com.google.protobuf.Parser<KeyValue> PARSER =
        new com.google.protobuf.AbstractParser<KeyValue>() {
      public KeyValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeyValue(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeyValue> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int valueCase_ = 0;
    private java.lang.Object value_;
    public enum ValueCase
        implements com.google.protobuf.Internal.EnumLite {
      INTEGERVAL(2),
      UINTEGERVAL(3),
      FLOATVAL(4),
      STRINGVAL(5),
      VALUE_NOT_SET(0);
      private int value = 0;
      private ValueCase(int value) {
        this.value = value;
      }
      public static ValueCase valueOf(int value) {
        switch (value) {
          case 2: return INTEGERVAL;
          case 3: return UINTEGERVAL;
          case 4: return FLOATVAL;
          case 5: return STRINGVAL;
          case 0: return VALUE_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ValueCase
    getValueCase() {
      return ValueCase.valueOf(
          valueCase_);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTEGERVAL_FIELD_NUMBER = 2;
    /**
     * <code>optional int32 integerVal = 2;</code>
     */
    public boolean hasIntegerVal() {
      return valueCase_ == 2;
    }
    /**
     * <code>optional int32 integerVal = 2;</code>
     */
    public int getIntegerVal() {
      if (valueCase_ == 2) {
        return (java.lang.Integer) value_;
      }
      return 0;
    }

    public static final int UINTEGERVAL_FIELD_NUMBER = 3;
    /**
     * <code>optional uint32 uIntegerVal = 3;</code>
     */
    public boolean hasUIntegerVal() {
      return valueCase_ == 3;
    }
    /**
     * <code>optional uint32 uIntegerVal = 3;</code>
     */
    public int getUIntegerVal() {
      if (valueCase_ == 3) {
        return (java.lang.Integer) value_;
      }
      return 0;
    }

    public static final int FLOATVAL_FIELD_NUMBER = 4;
    /**
     * <code>optional float floatVal = 4;</code>
     */
    public boolean hasFloatVal() {
      return valueCase_ == 4;
    }
    /**
     * <code>optional float floatVal = 4;</code>
     */
    public float getFloatVal() {
      if (valueCase_ == 4) {
        return (java.lang.Float) value_;
      }
      return 0F;
    }

    public static final int STRINGVAL_FIELD_NUMBER = 5;
    /**
     * <code>optional string stringVal = 5;</code>
     */
    public boolean hasStringVal() {
      return valueCase_ == 5;
    }
    /**
     * <code>optional string stringVal = 5;</code>
     */
    public java.lang.String getStringVal() {
      java.lang.Object ref = "";
      if (valueCase_ == 5) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8() && (valueCase_ == 5)) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stringVal = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStringValBytes() {
      java.lang.Object ref = "";
      if (valueCase_ == 5) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueCase_ == 5) {
          value_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (valueCase_ == 2) {
        output.writeInt32(
            2, (int)((java.lang.Integer) value_));
      }
      if (valueCase_ == 3) {
        output.writeUInt32(
            3, (int)((java.lang.Integer) value_));
      }
      if (valueCase_ == 4) {
        output.writeFloat(
            4, (float)((java.lang.Float) value_));
      }
      if (valueCase_ == 5) {
        output.writeBytes(5, getStringValBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (valueCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              2, (int)((java.lang.Integer) value_));
      }
      if (valueCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(
              3, (int)((java.lang.Integer) value_));
      }
      if (valueCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(
              4, (float)((java.lang.Float) value_));
      }
      if (valueCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getStringValBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serviceCommon.KeyValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serviceCommon.KeyValue)
        serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return serviceCommon.UpmuStructKeyValueListProtobuf.internal_static_serviceCommon_KeyValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return serviceCommon.UpmuStructKeyValueListProtobuf.internal_static_serviceCommon_KeyValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.class, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.Builder.class);
      }

      // Construct using serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        valueCase_ = 0;
        value_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return serviceCommon.UpmuStructKeyValueListProtobuf.internal_static_serviceCommon_KeyValue_descriptor;
      }

      public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue getDefaultInstanceForType() {
        return serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.getDefaultInstance();
      }

      public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue build() {
        serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue buildPartial() {
        serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue result = new serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (valueCase_ == 2) {
          result.value_ = value_;
        }
        if (valueCase_ == 3) {
          result.value_ = value_;
        }
        if (valueCase_ == 4) {
          result.value_ = value_;
        }
        if (valueCase_ == 5) {
          result.value_ = value_;
        }
        result.bitField0_ = to_bitField0_;
        result.valueCase_ = valueCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue) {
          return mergeFrom((serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue other) {
        if (other == serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        switch (other.getValueCase()) {
          case INTEGERVAL: {
            setIntegerVal(other.getIntegerVal());
            break;
          }
          case UINTEGERVAL: {
            setUIntegerVal(other.getUIntegerVal());
            break;
          }
          case FLOATVAL: {
            setFloatVal(other.getFloatVal());
            break;
          }
          case STRINGVAL: {
            valueCase_ = 5;
            value_ = other.value_;
            onChanged();
            break;
          }
          case VALUE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int valueCase_ = 0;
      private java.lang.Object value_;
      public ValueCase
          getValueCase() {
        return ValueCase.valueOf(
            valueCase_);
      }

      public Builder clearValue() {
        valueCase_ = 0;
        value_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional int32 integerVal = 2;</code>
       */
      public boolean hasIntegerVal() {
        return valueCase_ == 2;
      }
      /**
       * <code>optional int32 integerVal = 2;</code>
       */
      public int getIntegerVal() {
        if (valueCase_ == 2) {
          return (java.lang.Integer) value_;
        }
        return 0;
      }
      /**
       * <code>optional int32 integerVal = 2;</code>
       */
      public Builder setIntegerVal(int value) {
        valueCase_ = 2;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 integerVal = 2;</code>
       */
      public Builder clearIntegerVal() {
        if (valueCase_ == 2) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional uint32 uIntegerVal = 3;</code>
       */
      public boolean hasUIntegerVal() {
        return valueCase_ == 3;
      }
      /**
       * <code>optional uint32 uIntegerVal = 3;</code>
       */
      public int getUIntegerVal() {
        if (valueCase_ == 3) {
          return (java.lang.Integer) value_;
        }
        return 0;
      }
      /**
       * <code>optional uint32 uIntegerVal = 3;</code>
       */
      public Builder setUIntegerVal(int value) {
        valueCase_ = 3;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 uIntegerVal = 3;</code>
       */
      public Builder clearUIntegerVal() {
        if (valueCase_ == 3) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional float floatVal = 4;</code>
       */
      public boolean hasFloatVal() {
        return valueCase_ == 4;
      }
      /**
       * <code>optional float floatVal = 4;</code>
       */
      public float getFloatVal() {
        if (valueCase_ == 4) {
          return (java.lang.Float) value_;
        }
        return 0F;
      }
      /**
       * <code>optional float floatVal = 4;</code>
       */
      public Builder setFloatVal(float value) {
        valueCase_ = 4;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float floatVal = 4;</code>
       */
      public Builder clearFloatVal() {
        if (valueCase_ == 4) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional string stringVal = 5;</code>
       */
      public boolean hasStringVal() {
        return valueCase_ == 5;
      }
      /**
       * <code>optional string stringVal = 5;</code>
       */
      public java.lang.String getStringVal() {
        java.lang.Object ref = "";
        if (valueCase_ == 5) {
          ref = value_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (valueCase_ == 5) {
            if (bs.isValidUtf8()) {
              value_ = s;
            }
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stringVal = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStringValBytes() {
        java.lang.Object ref = "";
        if (valueCase_ == 5) {
          ref = value_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (valueCase_ == 5) {
            value_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stringVal = 5;</code>
       */
      public Builder setStringVal(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 5;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stringVal = 5;</code>
       */
      public Builder clearStringVal() {
        if (valueCase_ == 5) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional string stringVal = 5;</code>
       */
      public Builder setStringValBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 5;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:serviceCommon.KeyValue)
    }

    static {
      defaultInstance = new KeyValue(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:serviceCommon.KeyValue)
  }

  public interface KeyValueListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serviceCommon.KeyValueList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string category = 1;</code>
     */
    boolean hasCategory();
    /**
     * <code>required string category = 1;</code>
     */
    java.lang.String getCategory();
    /**
     * <code>required string category = 1;</code>
     */
    com.google.protobuf.ByteString
        getCategoryBytes();

    /**
     * <code>repeated .serviceCommon.KeyValue element = 2;</code>
     */
    java.util.List<serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue> 
        getElementList();
    /**
     * <code>repeated .serviceCommon.KeyValue element = 2;</code>
     */
    serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue getElement(int index);
    /**
     * <code>repeated .serviceCommon.KeyValue element = 2;</code>
     */
    int getElementCount();
    /**
     * <code>repeated .serviceCommon.KeyValue element = 2;</code>
     */
    java.util.List<? extends serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueOrBuilder> 
        getElementOrBuilderList();
    /**
     * <code>repeated .serviceCommon.KeyValue element = 2;</code>
     */
    serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueOrBuilder getElementOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code serviceCommon.KeyValueList}
   */
  public static final class KeyValueList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:serviceCommon.KeyValueList)
      KeyValueListOrBuilder {
    // Use KeyValueList.newBuilder() to construct.
    private KeyValueList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeyValueList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeyValueList defaultInstance;
    public static KeyValueList getDefaultInstance() {
      return defaultInstance;
    }

    public KeyValueList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeyValueList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              category_ = bs;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                element_ = new java.util.ArrayList<serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue>();
                mutable_bitField0_ |= 0x00000002;
              }
              element_.add(input.readMessage(serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          element_ = java.util.Collections.unmodifiableList(element_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return serviceCommon.UpmuStructKeyValueListProtobuf.internal_static_serviceCommon_KeyValueList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return serviceCommon.UpmuStructKeyValueListProtobuf.internal_static_serviceCommon_KeyValueList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.class, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.Builder.class);
    }

    public static com.google.protobuf.Parser<KeyValueList> PARSER =
        new com.google.protobuf.AbstractParser<KeyValueList>() {
      public KeyValueList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeyValueList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeyValueList> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CATEGORY_FIELD_NUMBER = 1;
    private java.lang.Object category_;
    /**
     * <code>required string category = 1;</code>
     */
    public boolean hasCategory() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string category = 1;</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          category_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string category = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ELEMENT_FIELD_NUMBER = 2;
    private java.util.List<serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue> element_;
    /**
     * <code>repeated .serviceCommon.KeyValue element = 2;</code>
     */
    public java.util.List<serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue> getElementList() {
      return element_;
    }
    /**
     * <code>repeated .serviceCommon.KeyValue element = 2;</code>
     */
    public java.util.List<? extends serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueOrBuilder> 
        getElementOrBuilderList() {
      return element_;
    }
    /**
     * <code>repeated .serviceCommon.KeyValue element = 2;</code>
     */
    public int getElementCount() {
      return element_.size();
    }
    /**
     * <code>repeated .serviceCommon.KeyValue element = 2;</code>
     */
    public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue getElement(int index) {
      return element_.get(index);
    }
    /**
     * <code>repeated .serviceCommon.KeyValue element = 2;</code>
     */
    public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueOrBuilder getElementOrBuilder(
        int index) {
      return element_.get(index);
    }

    private void initFields() {
      category_ = "";
      element_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCategory()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getElementCount(); i++) {
        if (!getElement(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCategoryBytes());
      }
      for (int i = 0; i < element_.size(); i++) {
        output.writeMessage(2, element_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCategoryBytes());
      }
      for (int i = 0; i < element_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serviceCommon.KeyValueList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serviceCommon.KeyValueList)
        serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return serviceCommon.UpmuStructKeyValueListProtobuf.internal_static_serviceCommon_KeyValueList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return serviceCommon.UpmuStructKeyValueListProtobuf.internal_static_serviceCommon_KeyValueList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.class, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.Builder.class);
      }

      // Construct using serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getElementFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        category_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (elementBuilder_ == null) {
          element_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          elementBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return serviceCommon.UpmuStructKeyValueListProtobuf.internal_static_serviceCommon_KeyValueList_descriptor;
      }

      public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList getDefaultInstanceForType() {
        return serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.getDefaultInstance();
      }

      public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList build() {
        serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList buildPartial() {
        serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList result = new serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.category_ = category_;
        if (elementBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            element_ = java.util.Collections.unmodifiableList(element_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.element_ = element_;
        } else {
          result.element_ = elementBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList) {
          return mergeFrom((serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList other) {
        if (other == serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.getDefaultInstance()) return this;
        if (other.hasCategory()) {
          bitField0_ |= 0x00000001;
          category_ = other.category_;
          onChanged();
        }
        if (elementBuilder_ == null) {
          if (!other.element_.isEmpty()) {
            if (element_.isEmpty()) {
              element_ = other.element_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureElementIsMutable();
              element_.addAll(other.element_);
            }
            onChanged();
          }
        } else {
          if (!other.element_.isEmpty()) {
            if (elementBuilder_.isEmpty()) {
              elementBuilder_.dispose();
              elementBuilder_ = null;
              element_ = other.element_;
              bitField0_ = (bitField0_ & ~0x00000002);
              elementBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getElementFieldBuilder() : null;
            } else {
              elementBuilder_.addAllMessages(other.element_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCategory()) {
          
          return false;
        }
        for (int i = 0; i < getElementCount(); i++) {
          if (!getElement(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object category_ = "";
      /**
       * <code>required string category = 1;</code>
       */
      public boolean hasCategory() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string category = 1;</code>
       */
      public java.lang.String getCategory() {
        java.lang.Object ref = category_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            category_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string category = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        java.lang.Object ref = category_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          category_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string category = 1;</code>
       */
      public Builder setCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string category = 1;</code>
       */
      public Builder clearCategory() {
        bitField0_ = (bitField0_ & ~0x00000001);
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      /**
       * <code>required string category = 1;</code>
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        category_ = value;
        onChanged();
        return this;
      }

      private java.util.List<serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue> element_ =
        java.util.Collections.emptyList();
      private void ensureElementIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          element_ = new java.util.ArrayList<serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue>(element_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.Builder, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueOrBuilder> elementBuilder_;

      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public java.util.List<serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue> getElementList() {
        if (elementBuilder_ == null) {
          return java.util.Collections.unmodifiableList(element_);
        } else {
          return elementBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public int getElementCount() {
        if (elementBuilder_ == null) {
          return element_.size();
        } else {
          return elementBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue getElement(int index) {
        if (elementBuilder_ == null) {
          return element_.get(index);
        } else {
          return elementBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public Builder setElement(
          int index, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue value) {
        if (elementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElementIsMutable();
          element_.set(index, value);
          onChanged();
        } else {
          elementBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public Builder setElement(
          int index, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.Builder builderForValue) {
        if (elementBuilder_ == null) {
          ensureElementIsMutable();
          element_.set(index, builderForValue.build());
          onChanged();
        } else {
          elementBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public Builder addElement(serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue value) {
        if (elementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElementIsMutable();
          element_.add(value);
          onChanged();
        } else {
          elementBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public Builder addElement(
          int index, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue value) {
        if (elementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElementIsMutable();
          element_.add(index, value);
          onChanged();
        } else {
          elementBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public Builder addElement(
          serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.Builder builderForValue) {
        if (elementBuilder_ == null) {
          ensureElementIsMutable();
          element_.add(builderForValue.build());
          onChanged();
        } else {
          elementBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public Builder addElement(
          int index, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.Builder builderForValue) {
        if (elementBuilder_ == null) {
          ensureElementIsMutable();
          element_.add(index, builderForValue.build());
          onChanged();
        } else {
          elementBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public Builder addAllElement(
          java.lang.Iterable<? extends serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue> values) {
        if (elementBuilder_ == null) {
          ensureElementIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, element_);
          onChanged();
        } else {
          elementBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public Builder clearElement() {
        if (elementBuilder_ == null) {
          element_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          elementBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public Builder removeElement(int index) {
        if (elementBuilder_ == null) {
          ensureElementIsMutable();
          element_.remove(index);
          onChanged();
        } else {
          elementBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.Builder getElementBuilder(
          int index) {
        return getElementFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueOrBuilder getElementOrBuilder(
          int index) {
        if (elementBuilder_ == null) {
          return element_.get(index);  } else {
          return elementBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public java.util.List<? extends serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueOrBuilder> 
           getElementOrBuilderList() {
        if (elementBuilder_ != null) {
          return elementBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(element_);
        }
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.Builder addElementBuilder() {
        return getElementFieldBuilder().addBuilder(
            serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.getDefaultInstance());
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.Builder addElementBuilder(
          int index) {
        return getElementFieldBuilder().addBuilder(
            index, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.getDefaultInstance());
      }
      /**
       * <code>repeated .serviceCommon.KeyValue element = 2;</code>
       */
      public java.util.List<serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.Builder> 
           getElementBuilderList() {
        return getElementFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.Builder, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueOrBuilder> 
          getElementFieldBuilder() {
        if (elementBuilder_ == null) {
          elementBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValue.Builder, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueOrBuilder>(
                  element_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          element_ = null;
        }
        return elementBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:serviceCommon.KeyValueList)
    }

    static {
      defaultInstance = new KeyValueList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:serviceCommon.KeyValueList)
  }

  public interface upmuStructKeyValueListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serviceCommon.upmuStructKeyValueList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 timeStamp = 1;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>required uint32 timeStamp = 1;</code>
     */
    int getTimeStamp();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
     */
    java.util.List<serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList> 
        getListList();
    /**
     * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
     */
    serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList getList(int index);
    /**
     * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
     */
    int getListCount();
    /**
     * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
     */
    java.util.List<? extends serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueListOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
     */
    serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueListOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code serviceCommon.upmuStructKeyValueList}
   */
  public static final class upmuStructKeyValueList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:serviceCommon.upmuStructKeyValueList)
      upmuStructKeyValueListOrBuilder {
    // Use upmuStructKeyValueList.newBuilder() to construct.
    private upmuStructKeyValueList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private upmuStructKeyValueList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final upmuStructKeyValueList defaultInstance;
    public static upmuStructKeyValueList getDefaultInstance() {
      return defaultInstance;
    }

    public upmuStructKeyValueList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private upmuStructKeyValueList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timeStamp_ = input.readUInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                list_ = new java.util.ArrayList<serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList>();
                mutable_bitField0_ |= 0x00000004;
              }
              list_.add(input.readMessage(serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return serviceCommon.UpmuStructKeyValueListProtobuf.internal_static_serviceCommon_upmuStructKeyValueList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return serviceCommon.UpmuStructKeyValueListProtobuf.internal_static_serviceCommon_upmuStructKeyValueList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList.class, serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList.Builder.class);
    }

    public static com.google.protobuf.Parser<upmuStructKeyValueList> PARSER =
        new com.google.protobuf.AbstractParser<upmuStructKeyValueList>() {
      public upmuStructKeyValueList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new upmuStructKeyValueList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<upmuStructKeyValueList> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private int timeStamp_;
    /**
     * <code>required uint32 timeStamp = 1;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 timeStamp = 1;</code>
     */
    public int getTimeStamp() {
      return timeStamp_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LIST_FIELD_NUMBER = 3;
    private java.util.List<serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList> list_;
    /**
     * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
     */
    public java.util.List<serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList> getListList() {
      return list_;
    }
    /**
     * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
     */
    public java.util.List<? extends serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueListOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
     */
    public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
     */
    public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueListOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private void initFields() {
      timeStamp_ = 0;
      name_ = "";
      list_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getListCount(); i++) {
        if (!getList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, timeStamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(3, list_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, timeStamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, list_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serviceCommon.upmuStructKeyValueList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serviceCommon.upmuStructKeyValueList)
        serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return serviceCommon.UpmuStructKeyValueListProtobuf.internal_static_serviceCommon_upmuStructKeyValueList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return serviceCommon.UpmuStructKeyValueListProtobuf.internal_static_serviceCommon_upmuStructKeyValueList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList.class, serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList.Builder.class);
      }

      // Construct using serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        timeStamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return serviceCommon.UpmuStructKeyValueListProtobuf.internal_static_serviceCommon_upmuStructKeyValueList_descriptor;
      }

      public serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList getDefaultInstanceForType() {
        return serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList.getDefaultInstance();
      }

      public serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList build() {
        serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList buildPartial() {
        serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList result = new serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList) {
          return mergeFrom((serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList other) {
        if (other == serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList.getDefaultInstance()) return this;
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000004);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimeStamp()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getListCount(); i++) {
          if (!getList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (serviceCommon.UpmuStructKeyValueListProtobuf.upmuStructKeyValueList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int timeStamp_ ;
      /**
       * <code>required uint32 timeStamp = 1;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 timeStamp = 1;</code>
       */
      public int getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>required uint32 timeStamp = 1;</code>
       */
      public Builder setTimeStamp(int value) {
        bitField0_ |= 0x00000001;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 timeStamp = 1;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timeStamp_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          list_ = new java.util.ArrayList<serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList>(list_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.Builder, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueListOrBuilder> listBuilder_;

      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public java.util.List<serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public Builder setList(
          int index, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public Builder setList(
          int index, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public Builder addList(serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public Builder addList(
          int index, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public Builder addList(
          serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public Builder addList(
          int index, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueListOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public java.util.List<? extends serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueListOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.getDefaultInstance());
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.getDefaultInstance());
      }
      /**
       * <code>repeated .serviceCommon.KeyValueList list = 3;</code>
       */
      public java.util.List<serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.Builder, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueListOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueList.Builder, serviceCommon.UpmuStructKeyValueListProtobuf.KeyValueListOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:serviceCommon.upmuStructKeyValueList)
    }

    static {
      defaultInstance = new upmuStructKeyValueList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:serviceCommon.upmuStructKeyValueList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serviceCommon_KeyValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serviceCommon_KeyValue_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serviceCommon_KeyValueList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serviceCommon_KeyValueList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serviceCommon_upmuStructKeyValueList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serviceCommon_upmuStructKeyValueList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$upmuStructKeyValueListProtobuf.proto\022\r" +
      "serviceCommon\"v\n\010KeyValue\022\013\n\003key\030\001 \002(\t\022\024" +
      "\n\nintegerVal\030\002 \001(\005H\000\022\025\n\013uIntegerVal\030\003 \001(" +
      "\rH\000\022\022\n\010floatVal\030\004 \001(\002H\000\022\023\n\tstringVal\030\005 \001" +
      "(\tH\000B\007\n\005value\"J\n\014KeyValueList\022\020\n\010categor" +
      "y\030\001 \002(\t\022(\n\007element\030\002 \003(\0132\027.serviceCommon" +
      ".KeyValue\"d\n\026upmuStructKeyValueList\022\021\n\tt" +
      "imeStamp\030\001 \002(\r\022\014\n\004name\030\002 \002(\t\022)\n\004list\030\003 \003" +
      "(\0132\033.serviceCommon.KeyValueList"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_serviceCommon_KeyValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_serviceCommon_KeyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_serviceCommon_KeyValue_descriptor,
        new java.lang.String[] { "Key", "IntegerVal", "UIntegerVal", "FloatVal", "StringVal", "Value", });
    internal_static_serviceCommon_KeyValueList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_serviceCommon_KeyValueList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_serviceCommon_KeyValueList_descriptor,
        new java.lang.String[] { "Category", "Element", });
    internal_static_serviceCommon_upmuStructKeyValueList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_serviceCommon_upmuStructKeyValueList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_serviceCommon_upmuStructKeyValueList_descriptor,
        new java.lang.String[] { "TimeStamp", "Name", "List", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
